/** Currency code → [country name, ISO alpha-2, ISO alpha-3] */
export const CURRENCY_COUNTRY = {
  USD: ['United States', 'US', 'USA'],
  AED: ['United Arab Emirates', 'AE', 'ARE'],
  AFN: ['Afghanistan', 'AF', 'AFG'],
  ALL: ['Albania', 'AL', 'ALB'],
  AMD: ['Armenia', 'AM', 'ARM'],
  ANG: ['Curaçao', 'CW', 'CUW'],
  AOA: ['Angola', 'AO', 'AGO'],
  ARS: ['Argentina', 'AR', 'ARG'],
  AUD: ['Australia', 'AU', 'AUS'],
  AWG: ['Aruba', 'AW', 'ABW'],
  AZN: ['Azerbaijan', 'AZ', 'AZE'],
  BAM: ['Bosnia and Herzegovina', 'BA', 'BIH'],
  BBD: ['Barbados', 'BB', 'BRB'],
  BDT: ['Bangladesh', 'BD', 'BGD'],
  BGN: ['Bulgaria', 'BG', 'BGR'],
  BHD: ['Bahrain', 'BH', 'BHR'],
  BIF: ['Burundi', 'BI', 'BDI'],
  BMD: ['Bermuda', 'BM', 'BMU'],
  BND: ['Brunei', 'BN', 'BRN'],
  BOB: ['Bolivia', 'BO', 'BOL'],
  BRL: ['Brazil', 'BR', 'BRA'],
  BSD: ['Bahamas', 'BS', 'BHS'],
  BTN: ['Bhutan', 'BT', 'BTN'],
  BWP: ['Botswana', 'BW', 'BWA'],
  BYN: ['Belarus', 'BY', 'BLR'],
  BZD: ['Belize', 'BZ', 'BLZ'],
  CAD: ['Canada', 'CA', 'CAN'],
  CDF: ['Democratic Republic of the Congo', 'CD', 'COD'],
  CHF: ['Switzerland', 'CH', 'CHE'],
  CLF: ['Chile (UF)', 'CL', 'CHL'],
  CLP: ['Chile', 'CL', 'CHL'],
  CNH: ['China (offshore)', 'CN', 'CHN'],
  CNY: ['China', 'CN', 'CHN'],
  COP: ['Colombia', 'CO', 'COL'],
  CRC: ['Costa Rica', 'CR', 'CRI'],
  CUP: ['Cuba', 'CU', 'CUB'],
  CVE: ['Cabo Verde', 'CV', 'CPV'],
  CZK: ['Czech Republic', 'CZ', 'CZE'],
  DJF: ['Djibouti', 'DJ', 'DJI'],
  DKK: ['Denmark', 'DK', 'DNK'],
  DOP: ['Dominican Republic', 'DO', 'DOM'],
  DZD: ['Algeria', 'DZ', 'DZA'],
  EGP: ['Egypt', 'EG', 'EGY'],
  ERN: ['Eritrea', 'ER', 'ERI'],
  ETB: ['Ethiopia', 'ET', 'ETH'],
  EUR: ['Germany', 'DE', 'DEU'],
  FJD: ['Fiji', 'FJ', 'FJI'],
  FKP: ['Falkland Islands', 'FK', 'FLK'],
  FOK: ['Faroe Islands', 'FO', 'FRO'],
  GBP: ['United Kingdom', 'GB', 'GBR'],
  GEL: ['Georgia', 'GE', 'GEO'],
  GGP: ['Guernsey', 'GG', 'GGY'],
  GHS: ['Ghana', 'GH', 'GHA'],
  GIP: ['Gibraltar', 'GI', 'GIB'],
  GMD: ['Gambia', 'GM', 'GMB'],
  GNF: ['Guinea', 'GN', 'GIN'],
  GTQ: ['Guatemala', 'GT', 'GTM'],
  GYD: ['Guyana', 'GY', 'GUY'],
  HKD: ['Hong Kong', 'HK', 'HKG'],
  HNL: ['Honduras', 'HN', 'HND'],
  HRK: ['Croatia', 'HR', 'HRV'],
  HTG: ['Haiti', 'HT', 'HTI'],
  HUF: ['Hungary', 'HU', 'HUN'],
  IDR: ['Indonesia', 'ID', 'IDN'],
  ILS: ['Israel', 'IL', 'ISR'],
  IMP: ['Isle of Man', 'IM', 'IMN'],
  INR: ['India', 'IN', 'IND'],
  IQD: ['Iraq', 'IQ', 'IRQ'],
  IRR: ['Iran', 'IR', 'IRN'],
  ISK: ['Iceland', 'IS', 'ISL'],
  JEP: ['Jersey', 'JE', 'JEY'],
  JMD: ['Jamaica', 'JM', 'JAM'],
  JOD: ['Jordan', 'JO', 'JOR'],
  JPY: ['Japan', 'JP', 'JPN'],
  KES: ['Kenya', 'KE', 'KEN'],
  KGS: ['Kyrgyzstan', 'KG', 'KGZ'],
  KHR: ['Cambodia', 'KH', 'KHM'],
  KID: ['Kiribati', 'KI', 'KIR'],
  KMF: ['Comoros', 'KM', 'COM'],
  KRW: ['South Korea', 'KR', 'KOR'],
  KWD: ['Kuwait', 'KW', 'KWT'],
  KYD: ['Cayman Islands', 'KY', 'CYM'],
  KZT: ['Kazakhstan', 'KZ', 'KAZ'],
  LAK: ['Laos', 'LA', 'LAO'],
  LBP: ['Lebanon', 'LB', 'LBN'],
  LKR: ['Sri Lanka', 'LK', 'LKA'],
  LRD: ['Liberia', 'LR', 'LBR'],
  LSL: ['Lesotho', 'LS', 'LSO'],
  LYD: ['Libya', 'LY', 'LBY'],
  MAD: ['Morocco', 'MA', 'MAR'],
  MDL: ['Moldova', 'MD', 'MDA'],
  MGA: ['Madagascar', 'MG', 'MDG'],
  MKD: ['North Macedonia', 'MK', 'MKD'],
  MMK: ['Myanmar', 'MM', 'MMR'],
  MNT: ['Mongolia', 'MN', 'MNG'],
  MOP: ['Macau', 'MO', 'MAC'],
  MRU: ['Mauritania', 'MR', 'MRT'],
  MUR: ['Mauritius', 'MU', 'MUS'],
  MVR: ['Maldives', 'MV', 'MDV'],
  MWK: ['Malawi', 'MW', 'MWI'],
  MXN: ['Mexico', 'MX', 'MEX'],
  MYR: ['Malaysia', 'MY', 'MYS'],
  MZN: ['Mozambique', 'MZ', 'MOZ'],
  NAD: ['Namibia', 'NA', 'NAM'],
  NGN: ['Nigeria', 'NG', 'NGA'],
  NIO: ['Nicaragua', 'NI', 'NIC'],
  NOK: ['Norway', 'NO', 'NOR'],
  NPR: ['Nepal', 'NP', 'NPL'],
  NZD: ['New Zealand', 'NZ', 'NZL'],
  OMR: ['Oman', 'OM', 'OMN'],
  PAB: ['Panama', 'PA', 'PAN'],
  PEN: ['Peru', 'PE', 'PER'],
  PGK: ['Papua New Guinea', 'PG', 'PNG'],
  PHP: ['Philippines', 'PH', 'PHL'],
  PKR: ['Pakistan', 'PK', 'PAK'],
  PLN: ['Poland', 'PL', 'POL'],
  PYG: ['Paraguay', 'PY', 'PRY'],
  QAR: ['Qatar', 'QA', 'QAT'],
  RON: ['Romania', 'RO', 'ROU'],
  RSD: ['Serbia', 'RS', 'SRB'],
  RUB: ['Russia', 'RU', 'RUS'],
  RWF: ['Rwanda', 'RW', 'RWA'],
  SAR: ['Saudi Arabia', 'SA', 'SAU'],
  SBD: ['Solomon Islands', 'SB', 'SLB'],
  SCR: ['Seychelles', 'SC', 'SYC'],
  SDG: ['Sudan', 'SD', 'SDN'],
  SEK: ['Sweden', 'SE', 'SWE'],
  SGD: ['Singapore', 'SG', 'SGP'],
  SHP: ['Saint Helena', 'SH', 'SHN'],
  SLE: ['Sierra Leone', 'SL', 'SLE'],
  SLL: ['Sierra Leone (old leone)', 'SL', 'SLE'],
  SOS: ['Somalia', 'SO', 'SOM'],
  SRD: ['Suriname', 'SR', 'SUR'],
  SSP: ['South Sudan', 'SS', 'SSD'],
  STN: ['Sao Tome and Principe', 'ST', 'STP'],
  SYP: ['Syria', 'SY', 'SYR'],
  SZL: ['Eswatini', 'SZ', 'SWZ'],
  THB: ['Thailand', 'TH', 'THA'],
  TJS: ['Tajikistan', 'TJ', 'TJK'],
  TMT: ['Turkmenistan', 'TM', 'TKM'],
  TND: ['Tunisia', 'TN', 'TUN'],
  TOP: ['Tonga', 'TO', 'TON'],
  TRY: ['Turkey', 'TR', 'TUR'],
  TTD: ['Trinidad and Tobago', 'TT', 'TTO'],
  TVD: ['Tuvalu', 'TV', 'TUV'],
  TWD: ['Taiwan', 'TW', 'TWN'],
  TZS: ['Tanzania', 'TZ', 'TZA'],
  UAH: ['Ukraine', 'UA', 'UKR'],
  UGX: ['Uganda', 'UG', 'UGA'],
  UYU: ['Uruguay', 'UY', 'URY'],
  UZS: ['Uzbekistan', 'UZ', 'UZB'],
  VES: ['Venezuela', 'VE', 'VEN'],
  VND: ['Vietnam', 'VN', 'VNM'],
  VUV: ['Vanuatu', 'VU', 'VUT'],
  WST: ['Samoa', 'WS', 'WSM'],
  XAF: ['Cameroon', 'CM', 'CMR'],
  XCD: ['Antigua and Barbuda', 'AG', 'ATG'],
  XCG: ['Caribbean Guilder region', 'CW', 'CUW'],
  XDR: ['IMF Special Drawing Rights', 'XD', 'XDR'],
  XOF: ['Senegal', 'SN', 'SEN'],
  XPF: ['French Polynesia', 'PF', 'PYF'],
  YER: ['Yemen', 'YE', 'YEM'],
  ZAR: ['South Africa', 'ZA', 'ZAF'],
  ZMW: ['Zambia', 'ZM', 'ZMB'],
  ZWG: ['Zimbabwe (ZiG)', 'ZW', 'ZWE'],
  ZWL: ['Zimbabwe', 'ZW', 'ZWE'],
};
